### ISSUE TITLE
Fix Portuguese accent in documentation

### ISSUE THREAD

**Issue by ryukinix** [ryukinix/decorating#11]
The project has pretty bad English. This should be fixed. All project docs were written in a hurry and I don't have much experience with writing english documentation so I do appreciate if someone help me with this.
- [x] README.md

**Comment by boxed** [comment]
Heh, even this ticket needs help with bad English. Let's try this:

"Fix Portuguese accent in documentation

The project has pretty bad English. This should be fixed."

I have absolutely no idea what "in XGo Horse mode on with a little of suicide naste." is even supposed to mean. It just sounds like random words thrown together.

**Comment by ghost** [comment]
Done! @boxed

**Comment by ghost** [comment]
#12

**Comment by ryukinix** [comment]
Hahahaha

**Comment by ryukinix** [comment]
Sorry for my autism

**Comment by ryukinix** [comment]
>  is even supposed to mean. It just sounds like random words thrown together.

Kill me please! :laughing:
