### ISSUE TITLE
You should make use of the decorator module

### ISSUE THREAD

**Issue by micheles** [ryukinix/decorating#13]
See https://github.com/micheles/decorator/blob/master/docs/README.rst

**Comment by ryukinix** [comment]
AWESOME module @micheles! Thanks for points this. In a future version I will try use that, for now I'm doing some experiments about decorators implementing from scratch just using the stdlib. 

Congratulations for `decorator`. Really great!

**Comment by ryukinix** [comment]
I prefer just use the stdlib. But thanks for points that, is a great lib.
