### ISSUE TITLE
Cache needs expiryTime (seconds)

### ISSUE THREAD

**Issue by pjz** [ryukinix/decorating#16]
Feature request:

Make the `cache` decorator accept an expiry time - the number of seconds that a result should be cached before re-running the wrapped function.  This is useful as a way to rate-limit queries to any kind of backing store.  The default of `None` would preserve the current behavior of caching 'forever'.

**Comment by ryukinix** [comment]
Nice Idea! Thanks for your contribution. I'll try that in some free time.
