### ISSUE TITLE
@animated gives an IndexError

### ISSUE THREAD

**Issue by rahiel** [ryukinix/decorating#2]
With version `decorating (0.2.1b0)` of the library, the following code:

``` python
from decorating import animated
from time import sleep

@animated
def main():
    sleep(300)

main()
```

gives me the traceback:

```
Traceback (most recent call last):
  File "test.py", line 8, in <module>
    main()
  File "/home/rahiel/Code/test/venv/lib/python3.5/site-packages/decorating/animation.py", line 159, in __call__
    if callable(args[0]):
IndexError: tuple index out of range
```

I've installed the package in a virtualenv.

Using `with animated(...)` works fine.

**Comment by onyb** [comment]
I saw this too. `master` branch works fine though.

**Comment by ryukinix** [comment]
WoW! Sorry for that, the pip package seems was deployed with a bug and I'm forgot to release a new fix for this because I'm trying do more things before a new release. (the release was yesterday). 

I'll fix in some minutes and I'll close this thread! Give a feedback later for me if works for you.

**Comment by ryukinix** [comment]
This was a simple [fix](https://github.com/ryukinix/decorating/commit/eb4a5f89e31a14b000d7eb8887f24227fdba31fe) I did following the release of `0.2.1b0`

**Comment by ryukinix** [comment]
@rahiel, I submitted right now a new version on  PyPI (v0.3). You can upgrade with `sudo pip install -U decorating` and running again your code? I'll be glad if works for you.

Feel free to reopen the issue if you have more problems with this, or open other if is another problem.

Thanks for the attention and feedback.

**Comment by rahiel** [comment]
@ryukinix that fixed it, thanks ;).
